//! The derived music pools: menu rotations borrowed from the radio, the
//! per-station host breaks, the station playlist and host maps, and the
//! whole-catalog duration index. Split from `music.rs` with `tables.rs`;
//! the names are re-exported from `music`.

use std::collections::HashMap;

use once_cell::sync::Lazy;

use super::expansion::NIGHT_LINE_VOCAL_TRACKS;
use super::tables::*;
use super::MusicTrack;

// Radio instrumentals that double as menu beds. Curated, not the whole
// instrumental catalog: these sit well under menu speech (Glass Highway and
// Lights Over Superior are the rockers, both by request), and the night picks
// stay behind the night theme so the day menu keeps its Americana feel. Vocal
// songs and host breaks stay on the radio -- menus already carry screen-reader
// speech. Borrowing a track does not take it off its station: every key here
// stays in the station playlist it came from.
fn radio_track_by_key(key: &str) -> MusicTrack {
    COUNTRY_TRACKS
        .iter()
        .chain(CLASSIC_ROCK_TRACKS.iter())
        .chain(BLUES_TRACKS.iter())
        .chain(std::iter::once(&*NIGHT_JAZZ_TRACK))
        .find(|track| track.key == key)
        .cloned()
        .unwrap_or_else(|| panic!("menu rotation names an unknown radio track: {key}"))
}

pub static MENU_DAY_ROTATION_TRACKS: Lazy<Vec<MusicTrack>> = Lazy::new(|| {
    [
        "radio_country_steel_string_sunday",
        "radio_country_dobro_dusk",
        "radio_rock_glass_highway",
        "radio_rock_lights_over_superior",
    ]
    .iter()
    .map(|key| radio_track_by_key(key))
    .collect()
});

pub static MENU_NIGHT_ROTATION_TRACKS: Lazy<Vec<MusicTrack>> = Lazy::new(|| {
    [
        "radio_blues_freight_yard_moon",
        "radio_blues_midnight_siding",
        "radio_night_low_beams",
    ]
    .iter()
    .map(|key| radio_track_by_key(key))
    .collect()
});

// Radio host segments, spoken between songs on the built-in and regional
// stations. ElevenLabs TTS clips, generated by tools/generate_radio.py; 8
// breaks per station (the asset contract in tools/radio_content_plan.py).
fn host_segments(
    slug: &str,
    station: &str,
    description: &str,
    durations: &[f64],
) -> Vec<MusicTrack> {
    durations
        .iter()
        .enumerate()
        .map(|(i, dur)| {
            let n = i + 1;
            MusicTrack::new(
                &format!("host_{slug}_{n:02}"),
                &format!("{station} host break {n}"),
                description,
                *dur,
            )
        })
        .collect()
}

/// `(host key, station name, description, eight break durations)`.
const HOST_TABLES: &[(&str, &str, &str, [f64; 8])] = &[
    (
        "roadhouse",
        "Freight Fate Roadhouse",
        "FFR host segment",
        [6.7, 4.9, 6.5, 6.4, 6.5, 6.6, 7.8, 7.0],
    ),
    (
        "nightline",
        "Freight Fate Night Line",
        "FFN host segment",
        [6.2, 6.0, 5.4, 5.2, 6.1, 5.9, 4.6, 7.4],
    ),
    (
        "rawhide",
        "The Rawhide 98.1",
        "KRWZ host segment",
        [5.1, 4.4, 4.7, 5.2, 4.6, 5.2, 5.3, 4.2],
    ),
    (
        "bigwheel",
        "Big Wheel Country 104.5",
        "WHWX host segment",
        [5.2, 6.0, 4.6, 4.4, 5.0, 4.5, 2.6, 3.3],
    ),
    (
        "prairieline",
        "Prairie Line 95.7",
        "KPNL host segment",
        [6.6, 6.2, 5.3, 5.7, 3.6, 4.9, 5.2, 3.9],
    ),
    (
        "bigsky",
        "Big Sky Country 99.3",
        "KBGK host segment",
        [7.7, 7.9, 6.2, 7.0, 6.3, 5.0, 5.6, 7.4],
    ),
    (
        "grind",
        "The Grind 97.9",
        "WGDX host segment",
        [5.2, 3.6, 5.7, 5.6, 4.2, 2.6, 6.0, 3.5],
    ),
    (
        "desertrock",
        "Desert Rock 101.5",
        "KDRZ host segment",
        [5.9, 5.9, 6.5, 6.1, 5.4, 3.6, 7.0, 3.8],
    ),
    (
        "chrome",
        "Chrome 106.3",
        "KHRZ host segment",
        [5.8, 4.5, 3.9, 5.1, 4.1, 3.8, 4.3, 3.7],
    ),
    (
        "ridge",
        "The Ridge 103.7",
        "KRIJ host segment",
        [5.5, 5.4, 4.4, 5.2, 4.1, 3.9, 3.9, 2.6],
    ),
    (
        "sound",
        "The Sound 102.1",
        "KSDX host segment",
        [4.6, 4.6, 3.9, 5.7, 4.2, 4.4, 4.6, 3.1],
    ),
    (
        "delta",
        "The Delta 94.3",
        "WDTQ host segment",
        [7.9, 5.0, 7.8, 6.3, 5.5, 8.1, 6.0, 5.3],
    ),
    (
        "bayou",
        "Bayou Soul 100.9",
        "WBYK host segment",
        [4.3, 3.6, 3.2, 4.5, 3.3, 2.6, 3.8, 2.9],
    ),
    (
        "southernsoul",
        "Southern Soul 96.5",
        "WSOZ host segment",
        [7.7, 4.5, 6.3, 9.1, 5.8, 7.9, 4.4, 4.8],
    ),
    (
        "afterhours",
        "Nashville After Hours 92.9",
        "WNAH host segment",
        [4.5, 5.6, 5.1, 4.1, 4.2, 4.3, 4.2, 3.2],
    ),
    (
        "cruisingold",
        "Cruisin' Gold 105.9",
        "KGOL host segment",
        [4.9, 5.9, 4.9, 5.3, 4.0, 5.5, 3.6, 2.9],
    ),
    (
        "gloryroad",
        "Glory Road 91.5",
        "WGLR host segment",
        [5.2, 4.6, 4.9, 7.3, 4.5, 4.7, 4.9, 3.8],
    ),
    (
        "purotejano",
        "Puro Tejano 107.1",
        "KTJO host segment",
        [5.5, 4.7, 5.0, 7.6, 6.0, 4.8, 4.9, 5.3],
    ),
    (
        "neondrive",
        "Neon Drive 88.5",
        "KNDR host segment",
        [4.7, 4.9, 5.2, 5.9, 3.8, 4.7, 4.5, 4.4],
    ),
];

fn host_pool(slug: &str) -> Vec<MusicTrack> {
    let (slug, station, description, durations) = HOST_TABLES
        .iter()
        .find(|(s, ..)| *s == slug)
        .expect("known host slug");
    host_segments(slug, station, description, durations)
}

pub static ROADHOUSE_HOST_SEGMENTS: Lazy<Vec<MusicTrack>> = Lazy::new(|| host_pool("roadhouse"));
pub static NIGHTLINE_HOST_SEGMENTS: Lazy<Vec<MusicTrack>> = Lazy::new(|| host_pool("nightline"));

/// The per-station host pools (`STATION_HOST_SEGMENTS`), in table order.
pub static STATION_HOST_SEGMENTS: Lazy<Vec<(String, Vec<MusicTrack>)>> = Lazy::new(|| {
    HOST_TABLES
        .iter()
        .map(|(slug, ..)| (slug.to_string(), host_pool(slug)))
        .collect()
});

/// The host pool for `host`, or an empty slice for a station with no voice.
pub fn station_host_segments(host: &str) -> &'static [MusicTrack] {
    STATION_HOST_SEGMENTS
        .iter()
        .find(|(slug, _)| slug == host)
        .map(|(_, pool)| pool.as_slice())
        .unwrap_or(&[])
}

/// The format pools (`STATION_PLAYLISTS`), in table order.
pub static STATION_PLAYLISTS: Lazy<Vec<(String, Vec<MusicTrack>)>> = Lazy::new(|| {
    let night: Vec<MusicTrack> = NIGHT_DRIVE_TRACKS
        .iter()
        .cloned()
        .chain(std::iter::once(NIGHT_JAZZ_TRACK.clone()))
        .chain(NIGHT_LINE_VOCAL_TRACKS.iter().cloned())
        .collect();
    vec![
        ("country".to_string(), COUNTRY_TRACKS.clone()),
        ("classic_rock".to_string(), CLASSIC_ROCK_TRACKS.clone()),
        ("blues".to_string(), BLUES_TRACKS.clone()),
        ("jazz".to_string(), JAZZ_TRACKS.clone()),
        ("night".to_string(), night),
        ("oldies".to_string(), OLDIES_TRACKS.clone()),
        ("gospel".to_string(), GOSPEL_TRACKS.clone()),
        ("tejano".to_string(), TEJANO_TRACKS.clone()),
        ("synthwave".to_string(), SYNTHWAVE_TRACKS.clone()),
    ]
});

/// The track pool for `playlist`, or an empty slice for an unknown one.
pub fn station_playlist(playlist: &str) -> &'static [MusicTrack] {
    STATION_PLAYLISTS
        .iter()
        .find(|(name, _)| name == playlist)
        .map(|(_, pool)| pool.as_slice())
        .unwrap_or(&[])
}

/// Songs played between host breaks on stations that have a host.
pub const RADIO_TRACKS_PER_HOST_BREAK: usize = 2;

pub static ALL_MUSIC_TRACKS: Lazy<Vec<MusicTrack>> = Lazy::new(|| {
    let mut all = Vec::new();
    all.extend(MENU_TRACKS.iter().cloned());
    all.extend(MENU_ROTATION_TRACKS.iter().cloned());
    all.push(MENU_NIGHT_TRACK.clone());
    all.extend(DAY_DRIVE_TRACKS.iter().cloned());
    all.extend(NIGHT_DRIVE_TRACKS.iter().cloned());
    all.extend(COUNTRY_TRACKS.iter().cloned());
    all.extend(CLASSIC_ROCK_TRACKS.iter().cloned());
    all.extend(BLUES_TRACKS.iter().cloned());
    all.extend(JAZZ_TRACKS.iter().cloned());
    all.push(NIGHT_JAZZ_TRACK.clone());
    all.extend(NIGHT_LINE_VOCAL_TRACKS.iter().cloned());
    all.extend(OLDIES_TRACKS.iter().cloned());
    all.extend(GOSPEL_TRACKS.iter().cloned());
    all.extend(TEJANO_TRACKS.iter().cloned());
    all.extend(SYNTHWAVE_TRACKS.iter().cloned());
    all
});

/// Spoken host breaks are deliberately short, so they live outside the music
/// catalog but share the duration lookup for rotation timing.
pub static ALL_HOST_SEGMENTS: Lazy<Vec<MusicTrack>> = Lazy::new(|| {
    STATION_HOST_SEGMENTS
        .iter()
        .flat_map(|(_, pool)| pool.iter().cloned())
        .collect()
});

pub(super) static TRACKS_BY_KEY: Lazy<HashMap<String, MusicTrack>> = Lazy::new(|| {
    ALL_MUSIC_TRACKS
        .iter()
        .chain(ALL_HOST_SEGMENTS.iter())
        .map(|track| (track.key.clone(), track.clone()))
        .collect()
});
