//! The achievement catalog: every badge and category. Originally generated
//! from `src/freight_fate/achievements.py`; since the Python gameplay
//! mirror retired (2026-08-29) this file is the source of truth, and new
//! badges are added here AND to the Python module (whose id list still
//! feeds the invariants export). The digest test pins the content against
//! accidental edits -- update it deliberately with each catalog change.
//!
//! Copy note (from the Python source): each badge has a specific
//! inspiration, but player-facing text uses song-title-level allusions and
//! broad themes only. Do not quote lyrics or recognizable lines, and never
//! put the artist's name in the name or description. A song title may
//! appear when it is simply a place or plain phrase (Jackson, Abilene); do
//! not show the source field in the in-game menu.

use super::{Achievement, AchievementCategory};

/// sha256 over every category and achievement field, as the generator
/// computed it from the Python catalog (see `catalog_digest` in the
/// tests for the exact framing).
pub const CATALOG_DIGEST: &str = "8a0be9ee9387f8edd9c1f913584275ad7af8d33adab0c0f6c2df8d43b7136d44";

/// What a locked, hidden achievement speaks in place of its real name and
/// description. Keeps a hidden badge's surprise -- the joke, the calendar
/// quirk -- intact until the driver actually earns it.
pub const HIDDEN_NAME: &str = "A Secret the Manifest Is Keeping";
pub const HIDDEN_HELP: &str = "Some badges don't announce themselves until you've earned them. Keep driving -- the road will tell you when you've found one.";

/// The category browse menu, modeled on the two-level achievements screen
/// from the owner's other game: pick a category, then arrow through its
/// badges. Titles carry a little of the game's voice; descriptions are the
/// one-line pitch spoken as menu help text. Every achievement below belongs
/// to exactly one of these.
pub const CATEGORIES: [AchievementCategory; 7] = [
    AchievementCategory {
        id: "road",
        title: "Out on the Road",
        description: "Clean runs, hard climbs, and the everyday work of hauling freight.",
    },
    AchievementCategory {
        id: "working_day",
        title: "The Working Day",
        description: "Rest breaks, inspections, traffic, and the rules that keep a driver legal.",
    },
    AchievementCategory {
        id: "career",
        title: "Career and Rank",
        description: "Levels, money, and trucks -- the long climb from hire to owner-operator.",
    },
    AchievementCategory {
        id: "radio_songs",
        title: "The Dial and Song Towns",
        description: "Stations you catch on the dial, and the towns those songs put on the map.",
    },
    AchievementCategory {
        id: "weather_seasons",
        title: "Weather and the Calendar",
        description: "Rain, snow, fog, and the seasons while you kept driving.",
    },
    AchievementCategory {
        id: "places",
        title: "Places on the Map",
        description: "Cities, states, and regions you hauled into.",
    },
    AchievementCategory {
        id: "hidden",
        title: "Deep Cuts",
        description: "A few badges even dispatch doesn't see coming.",
    },
];

/// Every badge, in the Python catalog's order (the achievements menu and
/// the cloud validator's allow-list both walk it in this order).
pub const ACHIEVEMENTS: [Achievement; 181] = [
    Achievement {
        id: "first_dispatch",
        name: "Breaker, Breaker",
        description: "You grabbed your first load off the board. No long line of trucks stacked up behind you yet, good buddy -- just a handle, a load number, and somewhere to be.",
        category: "career",
        inspiration: "C.W. McCall - Convoy",
        hidden: false,
    },
    Achievement {
        id: "first_pickup",
        name: "Loaded and Rolling",
        description: "Cargo's aboard and the seal is set. Eighteen wheels don't roll on by themselves -- somebody had to back it into the dock and sign for it first.",
        category: "career",
        inspiration: "Alabama - Roll On (Eighteen Wheeler)",
        hidden: false,
    },
    Achievement {
        id: "first_day",
        name: "First Day",
        description: "Dispatch handed you your first load number, the shipper watched you back a trailer into the dock, and the air finally built past governor release. Your first day is in the books.",
        category: "career",
        inspiration: "The Franklin County Trucking Company - I'm a Trucker",
        hidden: false,
    },
    Achievement {
        id: "first_delivery",
        name: "Signed, Sealed, Hauled",
        description: "Your very first load is signed for and gone. No fanfare needed -- the receiver got the freight and the paperwork held up clean.",
        category: "road",
        inspiration: "Dave Dudley - Truck Drivin' Son-of-a-Gun",
        hidden: false,
    },
    Achievement {
        id: "first_on_time",
        name: "Beat the Clock, Fewer Days",
        description: "You hit the dock before the deadline. Didn't take most of a week behind the wheel to manage it, and dispatch only ever reads the timestamp anyway.",
        category: "road",
        inspiration: "Dave Dudley - Six Days on the Road",
        hidden: false,
    },
    Achievement {
        id: "clean_delivery",
        name: "Pretty as a Billboard",
        description: "You delivered with barely a scratch on the rig. The truck's still pretty enough to smile down from a billboard -- not one new dent stealing the look.",
        category: "road",
        inspiration: "Del Reeves - Girl on the Billboard",
        hidden: false,
    },
    Achievement {
        id: "speed_limit_saint",
        name: "Slow Rod Lincoln",
        description: "A whole run and not one speeding strike. The souped-up itch tapped the throttle once, then you sat it down to think hard about the insurance.",
        category: "road",
        inspiration: "Commander Cody and His Lost Planet Airmen - Hot Rod Lincoln",
        hidden: false,
    },
    Achievement {
        id: "five_deliveries",
        name: "Just Can't Wait to Roll",
        description: "Five career deliveries logged. That itch to get rolling down the highway again finally has a stat line that agrees with you.",
        category: "career",
        inspiration: "Willie Nelson - On the Road Again",
        hidden: false,
    },
    Achievement {
        id: "ten_deliveries",
        name: "What a Long, Strange Haul",
        description: "Ten career deliveries in the books. It has been a long, strange stretch of road to get here, and the receipts are piling up faster than the war stories.",
        category: "career",
        inspiration: "Grateful Dead - Truckin'",
        hidden: false,
    },
    Achievement {
        id: "level_three",
        name: "Another Page, Another Town",
        description: "You reached career level 3. Here you are again, on stage in some new town -- except this chapter happens to pay better rates.",
        category: "career",
        inspiration: "Bob Seger - Turn the Page",
        hidden: false,
    },
    Achievement {
        id: "twenty_five_grand",
        name: "Built It a Piece at a Time",
        description: "You've banked 25,000 dollars, stacked up load by load. Slower than sneaking a Cadillac out of the plant in your lunchbox, but a whole lot more legal.",
        category: "career",
        inspiration: "Johnny Cash - One Piece at a Time",
        hidden: false,
    },
    Achievement {
        id: "thousand_miles",
        name: "Caught the White-Line Bug",
        description: "A thousand lifetime miles behind you. That white line gets in the blood like a fever, and the windshield's got the bug count to prove you've caught it.",
        category: "career",
        inspiration: "Merle Haggard - White Line Fever",
        hidden: false,
    },
    Achievement {
        id: "long_haul",
        name: "Where the Ribbon Don't End",
        description: "One loaded haul over 900 miles. The blacktop unspooled ahead like a ribbon with no end in sight, long enough for the seat cushion to earn seniority.",
        category: "road",
        inspiration: "Tiny Harris - Endless Black Ribbon",
        hidden: false,
    },
    Achievement {
        id: "state_crossing",
        name: "Kept It Between the Lines",
        description: "You crossed your first state line with freight aboard. One side to the other, you kept the rig between the lines and the load rode clean across the border.",
        category: "road",
        inspiration: "Johnny Cash - I Walk the Line",
        hidden: false,
    },
    Achievement {
        id: "multi_state",
        name: "Been Most Everywhere, Man",
        description: "One route, three states. Still working up to a list of towns long enough to rattle off in one breath, but the map had to stop and clear its throat.",
        category: "road",
        inspiration: "Hank Snow - I've Been Everywhere",
        hidden: false,
    },
    Achievement {
        id: "three_regions",
        name: "Three Regions and Ramblin'",
        description: "You've worked three freight regions now. Can't wait to get rolling out to the next one -- though dispatch still mispronounces wherever it turns out to be.",
        category: "road",
        inspiration: "Willie Nelson - On the Road Again",
        hidden: false,
    },
    Achievement {
        id: "toll_paid",
        name: "Bandit Pays the Toll",
        description: "You hit a toll and let the carrier eat it. Eastbound, westbound, loaded down -- one little beep at the booth, then accounting took the wheel.",
        category: "road",
        inspiration: "Jerry Reed - East Bound and Down",
        hidden: false,
    },
    Achievement {
        id: "no_toll_long",
        name: "Turns Out, an Easy Run",
        description: "Three hundred-plus loaded miles and not a single toll. They always swear no run comes easy -- this one clearly never got that memo.",
        category: "road",
        inspiration: "Dave Dudley - There Ain't No Easy Run",
        hidden: false,
    },
    Achievement {
        id: "rain_driver",
        name: "World Through a Wet Windshield",
        description: "You drove through the rain and kept it civil. The whole world goes by through that glass, with the wipers keeping time and your following distance keeping order.",
        category: "weather_seasons",
        inspiration: "Del Reeves - Looking at the World Through a Windshield",
        hidden: false,
    },
    Achievement {
        id: "winter_or_wind",
        name: "A Mile Past the Last Marker",
        description: "Snow or crosswind, you kept the trailer in line and the wheels turning. The kind of grim stretch that earns roadside markers stayed in your mirror, not the headlines.",
        category: "weather_seasons",
        inspiration: "Dick Curless - A Tombstone Every Mile",
        hidden: false,
    },
    Achievement {
        id: "low_visibility",
        name: "Foggy Mountain Haul",
        description: "You ran through fog thick enough to bend a banjo string and never lost the road. Headlights, GPS, and brake distance picked up the tune.",
        category: "weather_seasons",
        inspiration: "Flatt & Scruggs - Foggy Mountain Breakdown",
        hidden: false,
    },
    Achievement {
        id: "hazard_avoided",
        name: "Highway to Maybe Not",
        description: "You slowed in time to dodge a road hazard. Could've been a one-way ramp to somewhere awful -- your brake pedal had other plans.",
        category: "working_day",
        inspiration: "AC/DC - Highway to Hell",
        hidden: false,
    },
    Achievement {
        id: "construction_zone",
        name: "Honky-Tonk of Cones",
        description: "You crept through a construction zone like every cone had a lawyer on retainer. The swagger shrank down to posted speed, orange vests, and patient merging.",
        category: "working_day",
        inspiration: "John Anderson - Honky Tonk Crowd",
        hidden: false,
    },
    Achievement {
        id: "traffic_slowing",
        name: "Bumper-to-Bumper Blues",
        description: "Heavy traffic, and you kept the following distance sane. The road runs long and life moves fast on it, so you let the jam breathe instead of tailgating into a mess.",
        category: "working_day",
        inspiration: "Tom Cochrane - Life Is a Highway",
        hidden: false,
    },
    Achievement {
        id: "inspection",
        name: "Smokey at the Scale",
        description: "You rolled through an inspection with the paperwork in order. All that radio mischief stayed outside while your axle weights behaved themselves indoors.",
        category: "working_day",
        inspiration: "Rod Hart - C.B. Savage",
        hidden: false,
    },
    Achievement {
        id: "first_rest_stop",
        name: "Sweetheart of the Truck Stop",
        description: "You pulled into a rest stop for the very first time. The romance lasted exactly as long as the vending machine took to size you up and judge.",
        category: "working_day",
        inspiration: "The Willis Brothers - Truck Stop Cutie",
        hidden: false,
    },
    Achievement {
        id: "route_refuel",
        name: "Filler-Up and Keep Truckin'",
        description: "You topped off the tank before it got dramatic. Filled 'er up at the old roadside cafe and kept right on truckin' down the line.",
        category: "working_day",
        inspiration: "C.W. McCall - Old Home Filler-Up an' Keep On-a-Truckin' Cafe",
        hidden: false,
    },
    Achievement {
        id: "break_taken",
        name: "Coffee Break, Driver",
        description: "You took your 30-minute break and let the clock breathe. One more cup of truck-stop coffee, and your knees filed a note of gratitude.",
        category: "working_day",
        inspiration: "Buck Owens - Truck Drivin' Man",
        hidden: false,
    },
    Achievement {
        id: "slept_on_route",
        name: "Five-by-Two and Out",
        description: "Ten hours in the bunk and you woke up legal. Unglamorous sleeper math -- and somehow the most heroic move on the whole board.",
        category: "working_day",
        inspiration: "Red Simpson - Sleeper, Five-By-Two",
        hidden: false,
    },
    Achievement {
        id: "sleep_before_exhaustion",
        name: "Mama Warned You About This",
        description: "You bunked down before the fatigue started steering. Somebody once warned you about staring down that centerline too long -- this time you listened.",
        category: "working_day",
        inspiration: "Merle Haggard - Mama Tried",
        hidden: false,
    },
    Achievement {
        id: "garage_repair",
        name: "A Working Man's Receipt",
        description: "You fixed the rig in a proper garage instead of cobbling it together from borrowed parts. Honest work and an honest bill, and the truck rolled out earning its keep again.",
        category: "career",
        inspiration: "Merle Haggard - Workin' Man Blues",
        hidden: false,
    },
    Achievement {
        id: "first_upgrade",
        name: "Soup It Up a Little",
        description: "Your first upgrade -- a small taste of souped-up confidence. The ghost in that old hopped-up Lincoln approved, then asked why the invoice was so reasonable.",
        category: "career",
        inspiration: "Commander Cody and His Lost Planet Airmen - Hot Rod Lincoln",
        hidden: false,
    },
    Achievement {
        id: "heavy_hauler",
        name: "Eighteen Wheels and Then Some",
        description: "You bought the heavy hauler. The hills got a politely worded threat, and the fuel bill immediately demanded a speaking part of its own.",
        category: "career",
        inspiration: "Alabama - Roll On (Eighteen Wheeler)",
        hidden: false,
    },
    Achievement {
        id: "air_ready",
        name: "Star of the Interstate",
        description: "You built up enough air to kick the brakes loose like a pro. The glory goes to the compressor today -- even the fastest thing on the interstate needs its PSI.",
        category: "road",
        inspiration: "Deep Purple - Highway Star",
        hidden: false,
    },
    Achievement {
        id: "manual_driver",
        name: "Stick-Shift Solo",
        description: "You ran in manual and made the gearbox part of the band. Every clean shift sounds cool, right up until the grade changes key on you.",
        category: "road",
        inspiration: "Pete Drake - Gear Shiftin'",
        hidden: false,
    },
    Achievement {
        id: "eastbound_delivery",
        name: "Eastbound and Gone",
        description: "You ran a load net eastbound and put it on the dock. East is east, the hammer was down, and the receiver never had to wait on you.",
        category: "places",
        inspiration: "Jerry Reed - East Bound and Down",
        hidden: false,
    },
    Achievement {
        id: "westbound_delivery",
        name: "Westbound, Foot Down",
        description: "A load delivered headed the other way. Westbound and willing, you drank the weak coffee, pushed the sun down ahead of you, and put it on the dock.",
        category: "places",
        inspiration: "Little Feat - Willin'",
        hidden: false,
    },
    Achievement {
        id: "route66_run",
        name: "The Mother Road",
        description: "You hauled between two towns strung along the old Mother Road. The neon's faded, but the asphalt still gets its kicks under your tires.",
        category: "places",
        inspiration: "Bobby Troup - (Get Your Kicks on) Route 66",
        hidden: false,
    },
    Achievement {
        id: "amarillo_arrival",
        name: "Amarillo by Daybreak",
        description: "Rolled into Amarillo in the early light, the load on the dock by daybreak. You weren't quite riding in on a pony, but the Panhandle dawn made up the difference.",
        category: "places",
        inspiration: "George Strait - Amarillo by Morning",
        hidden: false,
    },
    Achievement {
        id: "phoenix_arrival",
        name: "Clear to Phoenix",
        description: "Freight delivered in Phoenix. By the time you rolled in, the desert had stopped pretending it was ever going to cool off.",
        category: "places",
        inspiration: "Glen Campbell - By the Time I Get to Phoenix",
        hidden: false,
    },
    Achievement {
        id: "wichita_arrival",
        name: "Wichita on the Line",
        description: "A load signed for in Wichita. Somewhere out on the plains a lineman waved; you were too busy watching the wind push the trailer.",
        category: "places",
        inspiration: "Glen Campbell - Wichita Lineman",
        hidden: false,
    },
    Achievement {
        id: "lubbock_arrival",
        name: "Lubbock in the Rearview",
        description: "Rolled out of Lubbock with a load, the high plains opening up ahead. They say happiness is a hometown shrinking in the rearview mirror, and tonight the freight led the way.",
        category: "places",
        inspiration: "Mac Davis - Texas in My Rear View Mirror",
        hidden: false,
    },
    Achievement {
        id: "bakersfield_arrival",
        name: "The Bakersfield Sound",
        description: "Freight on the dock in Bakersfield. The streets out here have a twang all their own, and your air brakes kept the beat.",
        category: "places",
        inspiration: "Dwight Yoakam & Buck Owens - Streets of Bakersfield",
        hidden: false,
    },
    Achievement {
        id: "tulsa_arrival",
        name: "Tulsa, Right on Schedule",
        description: "Pulled into Tulsa with the clock on your side and the load in on time. You ran it tight, and the dock was glad to see you right when they expected you.",
        category: "places",
        inspiration: "Don Williams - Tulsa Time",
        hidden: false,
    },
    Achievement {
        id: "vegas_arrival",
        name: "Long Live Las Vegas",
        description: "Hauled a load into Las Vegas without leaving a nickel in a machine. The only thing you gambled was the merge, and the house lost.",
        category: "places",
        inspiration: "Elvis Presley - Viva Las Vegas",
        hidden: false,
    },
    Achievement {
        id: "georgia_arrival",
        name: "Midnight Freight to Georgia",
        description: "Delivered somewhere in Georgia with the freight rolling in well after dark. No first-class ticket -- just a sleeper, a thermos, and a place you'd rather be.",
        category: "places",
        inspiration: "Gladys Knight & the Pips - Midnight Train to Georgia",
        hidden: false,
    },
    Achievement {
        id: "detroit_run",
        name: "Last Load Out of Detroit",
        description: "You hauled a load out of Detroit and pointed it down the road. The home you left keeps calling, but the freight pays better than the homesickness does.",
        category: "places",
        inspiration: "Bobby Bare - Detroit City",
        hidden: false,
    },
    Achievement {
        id: "all_regions",
        name: "Been Everywhere, For Real",
        description: "You've now hauled freight in all fourteen regions on the map. The list of towns is finally long enough to leave somebody breathless.",
        category: "places",
        inspiration: "Hank Snow - I've Been Everywhere",
        hidden: false,
    },
    Achievement {
        id: "coast_to_coast",
        name: "Coast-to-Coast Hauler",
        description: "One run that crossed most of a continent, salt air to salt air. Your seat cushion has seen more states this trip than most folks see in a year.",
        category: "road",
        inspiration: "Woody Guthrie - This Land Is Your Land",
        hidden: false,
    },
    Achievement {
        id: "fifty_deliveries",
        name: "Fifty Loads Down the Road",
        description: "Fifty career deliveries logged. The board knows your handle now, and the windshield's collected a small nation of bugs.",
        category: "career",
        inspiration: "Dave Dudley - Six Days on the Road",
        hidden: false,
    },
    Achievement {
        id: "hundred_deliveries",
        name: "Just Keep Rollin' On",
        description: "One hundred deliveries in the book. You never made a fuss about it, just kept the wheels rolling down the road, load after load, until the number turned serious.",
        category: "career",
        inspiration: "Lynyrd Skynyrd - Call Me the Breeze",
        hidden: false,
    },
    Achievement {
        id: "ten_thousand_miles",
        name: "Ten Thousand Down the Line",
        description: "Ten thousand lifetime miles behind you. The white-line fever stopped being a symptom a long way back -- now it's just the job.",
        category: "career",
        inspiration: "Merle Haggard - White Line Fever",
        hidden: false,
    },
    Achievement {
        id: "fifty_thousand_miles",
        name: "Highway Lifer",
        description: "Fifty thousand miles of trailers and two-lane towns behind you. You answer to a long ribbon of road now, and it is not the sort of job a person walks away from.",
        category: "career",
        inspiration: "Roger Miller - King of the Road",
        hidden: false,
    },
    Achievement {
        id: "hundred_grand",
        name: "Hundred-Grand Hood Ornament",
        description: "You've banked a hundred thousand dollars, one load at a time. Slow as smuggling a Cadillac out a piece at a time -- and a whole lot more legal.",
        category: "career",
        inspiration: "Johnny Cash - One Piece at a Time",
        hidden: false,
    },
    Achievement {
        id: "max_level",
        name: "Veteran of the Long Haul",
        description: "Career level twenty. Same towns, same docks, same diner pie -- but the page turns a little easier when you've read the whole book.",
        category: "career",
        inspiration: "Bob Seger - Turn the Page",
        hidden: false,
    },
    Achievement {
        id: "top_reputation",
        name: "CB Royalty",
        description: "Your reputation pinned the meter. Trailer for a throne, the whole channel knows the handle, and dispatch finally takes your word for it.",
        category: "career",
        inspiration: "Roger Miller - King of the Road",
        hidden: false,
    },
    Achievement {
        id: "perfect_streak",
        name: "Five Clean, In a Row",
        description: "Five straight deliveries on time, undamaged, and ticket-free. A streak that quiet doesn't make for a good CB story, but it pays.",
        category: "road",
        inspiration: "Red Simpson - I'm a Truck",
        hidden: false,
    },
    Achievement {
        id: "grueling_clean",
        name: "Long, Hard, and Spotless",
        description: "Twelve hundred-plus miles, on time, and not a fresh scratch on the rig. They swear no run comes easy; you delivered the exception.",
        category: "road",
        inspiration: "Dave Dudley - There Ain't No Easy Run",
        hidden: false,
    },
    Achievement {
        id: "big_payday",
        name: "Paid Like a Boss Hog",
        description: "One load cleared four grand gross all by itself. Just this once the big money landed squarely on the right side of the law, and the settlement sheet grinned back.",
        category: "career",
        inspiration: "Waylon Jennings - Good Ol' Boys",
        hidden: false,
    },
    Achievement {
        id: "mountain_clean",
        name: "Over the Rockies, Spotless",
        description: "You took a mountain grade and brought the freight down clean. The rocky high country tested the brakes; the brakes politely declined to fail.",
        category: "road",
        inspiration: "Joe Walsh - Rocky Mountain Way",
        hidden: false,
    },
    Achievement {
        id: "multi_leg_haul",
        name: "Four Legs and Rolling",
        description: "A single dispatch that strung four corridors together. Front to back it was a long line of road, and you ran the whole thing nose to tail.",
        category: "career",
        inspiration: "C.W. McCall - Convoy",
        hidden: false,
    },
    Achievement {
        id: "virginia_line",
        name: "Runnin' the County Line",
        description: "You put freight on a dock in Virginia, out where the ridgelines run the show. Some county lines out here are worth singing about; you crossed yours with the trailer full.",
        category: "places",
        inspiration: "49 Winchester - Russell County Line",
        hidden: false,
    },
    Achievement {
        id: "birmingham_morning",
        name: "Birmingham Before the Coffee Kicks In",
        description: "Freight delivered in Birmingham while the morning was still finding its feet. Eight-thirty in Alabama hits different when you have been rolling since before the birds.",
        category: "places",
        inspiration: "Andrea and Mud - Birmingham, AL 8:30AM",
        hidden: false,
    },
    Achievement {
        id: "kentucky_delivery",
        name: "Bluegrass on the Bill of Lading",
        description: "A load signed for in Kentucky, where the pastures look painted and the fences run forever. The grass gets called blue; the money you made on it was plain green.",
        category: "places",
        inspiration: "Brit Taylor - Kentucky Blue",
        hidden: false,
    },
    Achievement {
        id: "jersey_delivery",
        name: "Giant of the Turnpike",
        description: "You delivered in New Jersey and lived to merge again. Between the toll plazas and the jughandles, walking tall through Jersey takes a certain kind of nerve.",
        category: "places",
        inspiration: "Elle King - Jersey Giant",
        hidden: false,
    },
    Achievement {
        id: "waco_survivor",
        name: "Made It to Waco Just Fine",
        description: "Freight delivered in Waco without a scratch worth mentioning. Whatever the songs say about this town, you rolled in, got the signature, and kept your health intact.",
        category: "places",
        inspiration: "Croy and the Boys - Don't Let Me Die in Waco",
        hidden: false,
    },
    Achievement {
        id: "gulf_coast_by_two",
        name: "Coast Freight by Two O'Clock",
        description: "Delivered on the Mississippi Gulf coast with the clock still shy of two. Shrimp boats, salt air, and a bill of lading signed before the afternoon heat got serious.",
        category: "places",
        inspiration: "Ellis Bullard - Biloxi By Two",
        hidden: false,
    },
    Achievement {
        id: "nashville_delivery",
        name: "An Overnight Success, Eventually",
        description: "You put a load on a dock in Nashville, where every songwriter is ten years into being discovered any day now. Your freight got its big break on the first try.",
        category: "places",
        inspiration: "Curtis Grimes - Ten Year Town",
        hidden: false,
    },
    Achievement {
        id: "appalachia_delivery",
        name: "Freight Up the Holler",
        description: "You delivered into Appalachian coal-and-ridge country, where the roads bend like fiddle tunes. The hills watched you come in, and the dock was glad you did.",
        category: "places",
        inspiration: "Dirty Grass Soul - Back to the Holler",
        hidden: false,
    },
    Achievement {
        id: "wyoming_delivery",
        name: "Where the Herds Still Graze",
        description: "A delivery completed in Wyoming, high plains rolling out in every direction. Not much traffic to fight out here -- mostly wind, antelope, and the occasional legend.",
        category: "places",
        inspiration: "Chancey Williams - Land of the Buffalo",
        hidden: false,
    },
    Achievement {
        id: "norcal_giants",
        name: "Shadow of the Giants",
        description: "You delivered up in far Northern California, where the biggest living things on Earth watch the trucks go by. The trailer felt small the whole way in.",
        category: "places",
        inspiration: "Andrew Gabbard - Redwood",
        hidden: false,
    },
    Achievement {
        id: "pnw_delivery",
        name: "Pines to the Pacific",
        description: "Freight delivered in the Pacific Northwest, where the evergreens crowd the shoulders and the rain keeps its own schedule. The air alone was worth the trip.",
        category: "places",
        inspiration: "Colby Acuff - Western White Pines",
        hidden: false,
    },
    Achievement {
        id: "el_paso_arrival",
        name: "A Ballad Out West",
        description: "You brought freight into El Paso, the far west end of Texas. The old ballads about this town end in heartbreak; yours ended with a signed delivery receipt.",
        category: "places",
        inspiration: "Marty Robbins - El Paso City",
        hidden: false,
    },
    Achievement {
        id: "laredo_arrival",
        name: "Down the Old Cowboy Road",
        description: "Freight delivered in Laredo, right up against the border. The old song about this town is a slow goodbye; your visit was strictly business, and everybody stayed cheerful.",
        category: "places",
        inspiration: "Marty Robbins - Streets of Laredo",
        hidden: false,
    },
    Achievement {
        id: "baton_rouge_arrival",
        name: "Better Off Than Busted Flat",
        description: "You rolled into Baton Rouge with a load and a paycheck coming, which beats thumbing it with a harmonica. Freedom is nice; a settlement sheet is nicer.",
        category: "places",
        inspiration: "Kris Kristofferson - Me and Bobby McGee",
        hidden: false,
    },
    Achievement {
        id: "sacramento_arrival",
        name: "A Whistle Outside Folsom",
        description: "Freight delivered in Sacramento, just down the road from a famously well-sung prison. You heard a train whistle on the way in and kept rolling, free as you please.",
        category: "places",
        inspiration: "Johnny Cash - Folsom Prison Blues",
        hidden: false,
    },
    Achievement {
        id: "texas_triangle",
        name: "All Your Loads Live in Texas",
        description: "Origin and destination both inside the Texas triangle, one more load bouncing between the big towns. Some drivers spread out; this week the whole map was one state.",
        category: "places",
        inspiration: "George Strait - All My Ex's Live in Texas",
        hidden: false,
    },
    Achievement {
        id: "true_north_run",
        name: "The Compass Said Keep Going",
        description: "A delivery that ran hard north, latitude stacking up the whole way. When the wandering gets aimless, some folks find a bearing and follow it; yours had a dock at the end.",
        category: "road",
        inspiration: "Caroline Spence - True North",
        hidden: false,
    },
    Achievement {
        id: "southbound_run",
        name: "Down the Map with a Load",
        description: "A delivery that ran hard south, shedding latitude with every fuel stop. Warmer air, looser shoulders, and somebody at the bottom of the map waiting on freight.",
        category: "road",
        inspiration: "The Allman Brothers Band - Southbound",
        hidden: false,
    },
    Achievement {
        id: "return_trip",
        name: "Right Back Where You Started",
        description: "You delivered a load, then hauled the very next one straight back where you came from. Some drivers chase new horizons; this week the horizon ran a shuttle.",
        category: "road",
        inspiration: "Aaron McDonnell - You Drive Back",
        hidden: false,
    },
    Achievement {
        id: "all_terrain_route",
        name: "Flats, Foothills, and the Big Climb",
        description: "One route that served flat land, rolling hills, and a real mountain grade before the dock. Your stomach rode the whole ride; the freight never noticed a thing.",
        category: "road",
        inspiration: "Ellis Bullard - Roller Coaster",
        hidden: false,
    },
    Achievement {
        id: "long_day_run",
        name: "The Long Way to the Dock",
        description: "One dispatch that stretched past a full day on the trip clock, sleep and all. The kind of run where the last hundred miles feel personally aimed at you.",
        category: "road",
        inspiration: "Billy Strings - Long Journey Home",
        hidden: false,
    },
    Achievement {
        id: "reefer_load",
        name: "Cold Freight, Warm Heart",
        description: "Your first refrigerated load delivered with the temperature holding steady. The trailer ran cold the whole way there; no reason your mood had to.",
        category: "road",
        inspiration: "Hank Williams - Cold, Cold Heart",
        hidden: false,
    },
    Achievement {
        id: "heavy_haul_load",
        name: "Big John on the Drive Axles",
        description: "Your first heavy-haul load, the kind of tonnage that makes a trailer groan and a grade think twice. Every gear change felt like moving a legend.",
        category: "road",
        inspiration: "Jimmy Dean - Big Bad John",
        hidden: false,
    },
    Achievement {
        id: "high_value_load",
        name: "Sparkle in the Dry Van",
        description: "Your first high-value load delivered with the seals intact. Cargo worth more than the truck rides quiet, stays locked up tight, and never stops for souvenirs.",
        category: "road",
        inspiration: "Amanda Fields - Diamonds",
        hidden: false,
    },
    Achievement {
        id: "securement_load",
        name: "Chained and Checked",
        description: "Your first open-deck load delivered with every chain still tight. Fifty miles out you stopped and checked the tie-downs, the way the book says. Nothing shifted, nothing slid.",
        category: "road",
        inspiration: "Red Simpson - Roll, Truck, Roll",
        hidden: false,
    },
    Achievement {
        id: "tank_load",
        name: "The Load That Pushes Back",
        description: "Your first liquid bulk load delivered with the shell intact and the surge spent. Twenty-some tons of cargo spent the whole trip trying to drive. You did not let it.",
        category: "road",
        inspiration: "Dave Dudley - Six Days on the Road",
        hidden: false,
    },
    Achievement {
        id: "doubles_load",
        name: "Two Boxes, One Driver",
        description: "Your first twin-trailer set delivered whole. The rear pup wandered every mile and the mirrors never lied. Two hookups, two walk-arounds, one clean arrival.",
        category: "road",
        inspiration: "Red Sovine - Giddy-Up Go",
        hidden: false,
    },
    Achievement {
        id: "hazmat_load",
        name: "Placards Up",
        description: "Your first placarded load delivered without incident. Every scale watched you through, every restriction sign applied to you, and the paperwork rode shotgun. Careful pays.",
        category: "road",
        inspiration: "Merle Haggard - Movin' On",
        hidden: false,
    },
    Achievement {
        id: "port_load",
        name: "Through the Gate",
        description: "Your first container hauled off the secure side of the waterfront. The card got you through the gate; the chassis and the crane line did the rest. Salt air, steel boxes.",
        category: "road",
        inspiration: "Johnny Cash - I've Been Everywhere",
        hidden: false,
    },
    Achievement {
        id: "lcv_load",
        name: "The Long Combination",
        description: "Your first turnpike doubles run delivered. Two long trailers on the only corridors that allow them, and every lane change planned half a mile out. The certificate earned its keep.",
        category: "road",
        inspiration: "Dick Curless - A Tombstone Every Mile",
        hidden: false,
    },
    Achievement {
        id: "farm_load",
        name: "Feed, Seed, and Freight",
        description: "You hauled farm freight where it was needed -- feed, seed, or the season's grain. Somewhere down a gravel drive, a rancher checked the sky and said much obliged.",
        category: "road",
        inspiration: "Emily Nenni - On The Ranch",
        hidden: false,
    },
    Achievement {
        id: "max_gross_load",
        name: "Grossed Out at the Scale House",
        description: "You delivered a load pushing the legal weight limit, every axle earning its keep. The big mama of manifests, and the scale house waved it through anyway.",
        category: "road",
        inspiration: "Joe Stampley - Roll On Big Mama",
        hidden: false,
    },
    Achievement {
        id: "twenty_five_deliveries",
        name: "Twenty-Five and Rolling Steady",
        description: "Twenty-five career deliveries logged. Not a rookie number anymore, not a veteran number yet -- just a little more road behind you than most folks ever get.",
        category: "career",
        inspiration: "Ellie Turner - A Little Farther Down The Line",
        hidden: false,
    },
    Achievement {
        id: "two_hundred_deliveries",
        name: "Two Hundred and Playing for Keeps",
        description: "Two hundred career deliveries in the book. This stopped being a phase somewhere around load fifty; now it is a body of work with its own gravity.",
        category: "career",
        inspiration: "Emily Nenni - Long Game",
        hidden: false,
    },
    Achievement {
        id: "quarter_million_bank",
        name: "A Vault with Mud Flaps",
        description: "You banked 250,000 dollars, hauled in one settlement at a time. The teller stopped counting out loud somewhere around the third deposit. The bank is fine, by the way.",
        category: "career",
        inspiration: "Alex Miller - Breaking the Bank",
        hidden: false,
    },
    Achievement {
        id: "half_million_earned",
        name: "Half a Million in Lifetime Freight",
        description: "Five hundred thousand dollars in career earnings, gross of everything the road took back along the way. Nobody would call it easy money, but it spends just the same.",
        category: "career",
        inspiration: "Brit Taylor - Rich Little Girls",
        hidden: false,
    },
    Achievement {
        id: "hundred_k_miles",
        name: "Leave Me on the Interstate",
        description: "One hundred thousand lifetime miles. At this point the road owns a controlling share of you, and someday it can have the rest -- but not today, driver.",
        category: "career",
        inspiration: "Bob Wayne - Spread My Ashes on the Highway",
        hidden: false,
    },
    Achievement {
        id: "rep_ninety",
        name: "Strut Past the Fuel Island",
        description: "Reputation at ninety or better. Walk through any truck stop like you own the coffee machine, because at this point dispatch practically curtsies.",
        category: "career",
        inspiration: "Elvin Bishop - Struttin' My Stuff",
        hidden: false,
    },
    Achievement {
        id: "month_on_road",
        name: "Thirty Days of Diesel",
        description: "A full month on the career clock. Thirty days of docks, diners, and dawn departures -- and tomorrow you will get up and ask the road for another one.",
        category: "career",
        inspiration: "Ellie Turner - One More Day",
        hidden: false,
    },
    Achievement {
        id: "home_return",
        name: "The Porch Light Was Still On",
        description: "Ten deliveries or more into your career, you brought a load into your old home terminal city. The streets got smaller while you were gone; the welcome did not.",
        category: "career",
        inspiration: "Arlo McKinley - Back Home",
        hidden: false,
    },
    Achievement {
        id: "bobtail_done",
        name: "Room Enough to Turn Around",
        description: "You ran a bobtail reposition -- no trailer, no load, just a tractor finding its next job. Turning a rig around takes a lot less acreage without the box.",
        category: "career",
        inspiration: "The Willis Brothers - Give Me 40 Acres",
        hidden: false,
    },
    Achievement {
        id: "april_first",
        name: "Nobody's Fool on the First",
        description: "A delivery settled on the first day of April. Dispatch swore the load was real, and for once the joke was on nobody -- paperwork clean, payment posted.",
        category: "hidden",
        inspiration: "Bo Hazard - April's Fool",
        hidden: true,
    },
    Achievement {
        id: "winter_delivery",
        name: "December Never Stood a Chance",
        description: "A load delivered in the dead of winter, heater roaring and shoulders tight. The cold months lean hard on a trucking family; you leaned back and kept rolling.",
        category: "weather_seasons",
        inspiration: "Merle Haggard - If We Make It Through December",
        hidden: false,
    },
    Achievement {
        id: "four_seasons",
        name: "All Four Pages of the Calendar",
        description: "You have settled deliveries in spring, summer, fall, and winter. The road changes clothes four times a year, and you have now seen the whole wardrobe.",
        category: "weather_seasons",
        inspiration: "George Jones - Seasons of My Heart",
        hidden: false,
    },
    Achievement {
        id: "desert_summer",
        name: "Through the Furnace Door",
        description: "A summer delivery into the desert Southwest, where the asphalt shimmers and the door handle can bite. Whatever is on the other side of hot, you drove through it.",
        category: "weather_seasons",
        inspiration: "Emily Nenni - Gates Of Hell",
        hidden: false,
    },
    Achievement {
        id: "weather_collector",
        name: "Every Sky in the Logbook",
        description: "You have driven under every kind of sky the forecast can throw: sun, cloud, rain, downpour, thunder, snow, fog, and wind. None of it lasted; you did.",
        category: "weather_seasons",
        inspiration: "Waylon Jennings & Jessi Colter - Storms Never Last",
        hidden: false,
    },
    Achievement {
        id: "storm_driving",
        name: "Dark Line on the Radar",
        description: "You drove through a genuine thunderstorm and kept the trailer behind you where it belongs. You could feel the weather coming on long before the first drop hit.",
        category: "weather_seasons",
        inspiration: "Channing Wilson - Blues Comin' On",
        hidden: false,
    },
    Achievement {
        id: "deadline_squeaker",
        name: "Hot Brakes, Warm Handshake",
        description: "On time with almost nothing to spare -- the kind of arrival where the dock crew was already drafting the late note. They tore it up, and you never saw it.",
        category: "road",
        inspiration: "Brennen Leigh & Asleep At The Wheel - Comin' In Hot",
        hidden: false,
    },
    Achievement {
        id: "first_late",
        name: "Keep the Bonus, Boss",
        description: "Your first late delivery is on the books. The bonus walked, the receiver sighed, and you learned exactly how much of a deadline is actually cushion.",
        category: "road",
        inspiration: "Johnny Paycheck - Take This Job and Shove It",
        hidden: false,
    },
    Achievement {
        id: "midnight_delivery",
        name: "The Small Hours Ride Along",
        description: "Freight delivered in the smallest hours, between midnight and the first hint of gray. Whatever kept you company out there signed nothing and vanished at the dock.",
        category: "road",
        inspiration: "Dolly Parton & Ben Haggard - Demons",
        hidden: false,
    },
    Achievement {
        id: "dawn_run",
        name: "Rolling Before the Roosters",
        description: "You pulled out before the world got loud, first light still rehearsing on the horizon. The early start echoes all day -- mostly in yawns, occasionally in bonuses.",
        category: "road",
        inspiration: "American Aquarium - Waking Up the Echoes",
        hidden: false,
    },
    Achievement {
        id: "fuel_fumes",
        name: "Hope Is Not a Fuel Plan",
        description: "You made the dock with the fuel gauge past pleading and into prayer. Somewhere back down the road you passed the last cheap diesel and said, probably fine.",
        category: "road",
        inspiration: "Brennen Leigh - Running Out Of Hope, Arkansas",
        hidden: false,
    },
    Achievement {
        id: "spotless_long",
        name: "Vanished Like a Professional",
        description: "Three hundred-plus miles delivered on time with no damage, no strikes, and no tickets. In and out so smooth the paperwork is the only proof you were there.",
        category: "road",
        inspiration: "Caroline Spence - Clean Getaway",
        hidden: false,
    },
    Achievement {
        id: "first_ticket",
        name: "Yeah, Officer, That Was Me",
        description: "Your first on-the-spot speeding ticket, signed and paid at the roadside. When dispatch heard, they did not even sound surprised -- which stings worse than the fine.",
        category: "working_day",
        inspiration: "Drake Milligan - Sounds Like Something I'd Do",
        hidden: false,
    },
    Achievement {
        id: "second_ticket",
        name: "Twice in One Trip, Really",
        description: "Two speeding tickets inside a single run. The first one was a lesson; the second one was a decision. The trooper recognized the truck, which is never a good sign.",
        category: "working_day",
        inspiration: "Erin Viancourt - Should've Known Better",
        hidden: false,
    },
    Achievement {
        id: "jam_and_cones",
        name: "Stuck in Every Flavor of Slow",
        description: "Construction cones and a genuine traffic jam, both inside one trip. For a while there the truck was less a vehicle and more a waiting room with mud flaps.",
        category: "working_day",
        inspiration: "Christian Parker - You Ain't Going Nowhere",
        hidden: false,
    },
    Achievement {
        id: "scale_regular",
        name: "On a First-Name Basis at the Scale",
        description: "Five inspections weathered across your career. The scale house is a wall every driver has to get over sooner or later; by now you could climb it in your sleep.",
        category: "working_day",
        inspiration: "Caroline Spence - Scale These Walls",
        hidden: false,
    },
    Achievement {
        id: "all_upgrades",
        name: "Every Box on the Order Sheet",
        description: "Every upgrade in the catalog installed on your rig. They quit building cars like they used to, but a fully optioned tractor still turns heads at the fuel island.",
        category: "career",
        inspiration: "Dale Watson - Whatever Happened To The Cadillac",
        hidden: false,
    },
    Achievement {
        id: "deep_repair",
        name: "Back from the Bottom of the Ledger",
        description: "You brought the truck in at seventy-five percent damage or worse and paid to make it whole. There is only one direction to go from down there, and you took it.",
        category: "career",
        inspiration: "Alex Williams - Rock Bottom",
        hidden: false,
    },
    Achievement {
        id: "roadside_fix",
        name: "The Show Rolls On",
        description: "Broke down bad enough to call for roadside help, waited out the mechanic, and finished the run anyway. Every touring act has a night like this; yours had freight.",
        category: "career",
        inspiration: "Dale Watson & Ray Benson - Bus' Breakdown",
        hidden: false,
    },
    Achievement {
        id: "level_five",
        name: "Regular on the Regional Board",
        description: "Career level five. Dispatch stopped double-checking your paperwork, the lanes run a little wider, and you can even turn a load down without getting a lecture.",
        category: "career",
        inspiration: "Merle Haggard - Workin' Man Blues",
        hidden: false,
    },
    Achievement {
        id: "level_ten",
        name: "Lead Driver, Says So on the Vest",
        description: "Career level ten and senior status at the carrier. Premium freight, a deeper board, and new hires who assume you know where every dock in the country hides.",
        category: "career",
        inspiration: "Alabama - Forty Hour Week (For a Livin')",
        hidden: false,
    },
    Achievement {
        id: "level_fifteen",
        name: "Halfway Up the Ladder",
        description: "Career level fifteen. The working-capital target is taped to the sun visor now, and the owner-operator checklist reads less like a dream and more like a plan.",
        category: "career",
        inspiration: "Dolly Parton - 9 to 5",
        hidden: false,
    },
    Achievement {
        id: "level_twenty_five",
        name: "Qualified for Your Own Numbers",
        description: "Career level twenty-five. Whether or not you ever file the paperwork, this career now qualifies for its own operating authority. In freight, that counts as arriving.",
        category: "career",
        inspiration: "Waylon Jennings - Are You Sure Hank Done It This Way",
        hidden: false,
    },
    Achievement {
        id: "level_thirty",
        name: "All the Way to the Top Rung",
        description: "Career level thirty, the top of the ladder. Every rank, every gate, every unlock -- the whole climb is behind you, and the road ahead is simply yours to choose.",
        category: "career",
        inspiration: "Roger Miller - King of the Road",
        hidden: false,
    },
    Achievement {
        id: "fleet_upgrade",
        name: "Newer Iron from the Yard",
        description: "Dispatch swapped your assigned tractor for a newer fleet unit, handed over fueled, serviced, and washed. Seniority has a smell, and it is fresh upholstery.",
        category: "career",
        inspiration: "Dale Watson - Truckin' Man",
        hidden: false,
    },
    Achievement {
        id: "fleet_flagship",
        name: "First Pick of the Yard",
        description: "You reached the top of the company fleet: the flagship tractor with the big bunk and the long legs. The yard hands you the keys before anyone else gets asked.",
        category: "career",
        inspiration: "Red Sovine - Phantom 309",
        hidden: false,
    },
    Achievement {
        id: "three_trucks",
        name: "A Yard of Your Own",
        description: "Three tractors with your name on the titles. Call it a fleet if you like; the insurance folder certainly does. Somebody still has to drive them all, though.",
        category: "career",
        inspiration: "Kathy Mattea - Eighteen Wheels and a Dozen Roses",
        hidden: false,
    },
    Achievement {
        id: "owner_operator_buyin",
        name: "Your Name on the Title",
        description: "You bought into your first tractor position as a leased-on owner-operator. The revenue is bigger, the bills are yours, and so is every decision from here on.",
        category: "career",
        inspiration: "Red Simpson - I'm a Truck",
        hidden: false,
    },
    Achievement {
        id: "authority_active",
        name: "Running Under Your Own Numbers",
        description: "Own authority is active: your freight, your rates, your compliance folder. Nobody left to lease the risk to, and nobody to hand the upside to either.",
        category: "career",
        inspiration: "Hank Williams Jr. - A Country Boy Can Survive",
        hidden: false,
    },
    Achievement {
        id: "self_paid_course",
        name: "Paid for the Classroom Yourself",
        description: "You bought an endorsement course with your own money instead of waiting on carrier sponsorship. Ambition has tuition, and you covered it in cash at the counter.",
        category: "career",
        inspiration: "Aaron Tippin - Working Man's Ph.D.",
        hidden: false,
    },
    Achievement {
        id: "twenty_five_cities",
        name: "Twenty-Five Pins in the Map",
        description: "Deliveries settled in twenty-five different cities. The atlas in the door pocket is starting to fall open to the right page all on its own.",
        category: "places",
        inspiration: "Hank Snow - I've Been Everywhere",
        hidden: false,
    },
    Achievement {
        id: "seventy_five_cities",
        name: "Seventy-Five Docks Deep",
        description: "Seventy-five different cities have signed for your freight. Receivers you have never met already know the truck, and somehow the coffee is bad in every one.",
        category: "places",
        inspiration: "Willie Nelson - Still Is Still Moving to Me",
        hidden: false,
    },
    Achievement {
        id: "hundred_fifty_cities",
        name: "Half the Map, Signed For",
        description: "One hundred fifty cities delivered. On a map of six hundred some towns that is a serious dent, and the far side of the country is starting to feel left out.",
        category: "places",
        inspiration: "Alan Jackson - Drive (For Daddy Gene)",
        hidden: false,
    },
    Achievement {
        id: "fifteen_states",
        name: "Fifteen State Lines Behind You",
        description: "You have delivered freight in fifteen different states. The trailer plate is a conversation starter now, and the glovebox is mostly toll receipts.",
        category: "places",
        inspiration: "Bobby Bare - 500 Miles Away from Home",
        hidden: false,
    },
    Achievement {
        id: "thirty_states",
        name: "Thirty States and Counting",
        description: "Thirty states have taken freight off your trailer. Most folks need a lifetime and a camper to see that much country; you did it hauling other people's furniture.",
        category: "places",
        inspiration: "Johnny Cash - Ride This Train",
        hidden: false,
    },
    Achievement {
        id: "dakota_delivery",
        name: "Freight for the High Plains",
        description: "A load delivered into the Dakotas, where the horizon does most of the talking and the wind files a counterclaim. Somebody has to keep the prairie stocked.",
        category: "places",
        inspiration: "Corb Lund - Long Gone to Saskatchewan",
        hidden: false,
    },
    Achievement {
        id: "montana_delivery",
        name: "Under the Biggest Sky",
        description: "Freight settled in Montana, where the interstate runs long, the radio runs out, and the sky goes on far past the windshield. Worth the mileage every single time.",
        category: "places",
        inspiration: "Merle Haggard - Big City",
        hidden: false,
    },
    Achievement {
        id: "new_england_delivery",
        name: "Down East with a Dry Van",
        description: "A delivery into northern New England: narrow bridges, frost heaves, and town names that pick fights with the GPS. The chowder alone justifies the deadhead home.",
        category: "places",
        inspiration: "Dick Curless - A Tombstone Every Mile",
        hidden: false,
    },
    Achievement {
        id: "muskogee_arrival",
        name: "Still Proud in Muskogee",
        description: "A load delivered into Muskogee, Oklahoma, where folks still take pride in living right and shaking your hand. Clean paperwork counts as manners out here.",
        category: "radio_songs",
        inspiration: "Merle Haggard - Okie From Muskogee",
        hidden: false,
    },
    Achievement {
        id: "kansas_city_arrival",
        name: "Brighter Than the Local TV Star",
        description: "Freight delivered into Kansas City, home of burnt ends, wide boulevards, and local celebrities who will not help you back into a dock. You managed anyway.",
        category: "radio_songs",
        inspiration: "Roger Miller - Kansas City Star",
        hidden: false,
    },
    Achievement {
        id: "memphis_arrival",
        name: "However You Got to Memphis",
        description: "Freight put down in Memphis, at the top of the Delta where the river hauls nearly as much as the highway. Whatever brought you here, the dock only asked for the bills.",
        category: "radio_songs",
        inspiration: "Tom T. Hall - That's How I Got to Memphis",
        hidden: false,
    },
    Achievement {
        id: "saginaw_arrival",
        name: "Cold Bay, Warm Welcome",
        description: "A delivery into Saginaw, up where the bay wind finds every gap in the cab insulation. Half the town works the water; the freight still comes in by road.",
        category: "radio_songs",
        inspiration: "Lefty Frizzell - Saginaw, Michigan",
        hidden: false,
    },
    Achievement {
        id: "fort_worth_arrival",
        name: "Cowtown Crossed Your Mind",
        description: "A load delivered into Fort Worth, where the stockyards went showbiz but the freight stayed honest. Dallas sits close enough to wave at and far enough to ignore.",
        category: "radio_songs",
        inspiration: "George Strait - Does Fort Worth Ever Cross Your Mind",
        hidden: false,
    },
    Achievement {
        id: "san_antonio_arrival",
        name: "Backing Down to San Antone",
        description: "Freight settled in San Antonio, down where the missions keep their bells and the breakfast tacos outrank the barbecue. The river walks; your trailer rolled.",
        category: "radio_songs",
        inspiration: "Bob Wills & His Texas Playboys - New San Antonio Rose",
        hidden: false,
    },
    Achievement {
        id: "new_orleans_arrival",
        name: "Good Morning, Crescent City",
        description: "A load brought into New Orleans, past the wards and the water, where even the freight moves a little behind the beat. Nobody minded, and the coffee fixed it.",
        category: "radio_songs",
        inspiration: "Willie Nelson - City of New Orleans",
        hidden: false,
    },
    Achievement {
        id: "houston_arrival",
        name: "One Day Closer, Says the Odometer",
        description: "Freight delivered into Houston, a city sprawling far enough to have its own weather and at least four rush hours. Every mile of it counted toward somewhere that matters.",
        category: "radio_songs",
        inspiration: "Larry Gatlin & The Gatlin Brothers - Houston (Means I'm One Day Closer to You)",
        hidden: false,
    },
    Achievement {
        id: "winslow_arrival",
        name: "A Corner Worth Standing On",
        description: "A load delivered into Winslow, a small Arizona town with one world-famous corner. Park the rig, stretch your legs, and enjoy being the second-most photographed thing downtown.",
        category: "radio_songs",
        inspiration: "Eagles - Take It Easy",
        hidden: false,
    },
    Achievement {
        id: "chattanooga_arrival",
        name: "Quicker Than the Old Express",
        description: "Freight rolled into Chattanooga ahead of anything on rails, through the ridge cuts where the river bends twice to look around. The old trains would have needed a schedule.",
        category: "radio_songs",
        inspiration: "Glenn Miller - Chattanooga Choo Choo",
        hidden: false,
    },
    Achievement {
        id: "jackson_arrival",
        name: "The Jackson Everybody Sings About",
        description: "A load delivered into Jackson. Folks have argued for sixty years over which Jackson the song means, Tennessee or Mississippi, so this badge takes either. Your bill of lading, at least, is specific.",
        category: "radio_songs",
        inspiration: "Johnny Cash & June Carter - Jackson",
        hidden: false,
    },
    Achievement {
        id: "abilene_arrival",
        name: "Prettiest Town on the Manifest",
        description: "Freight delivered into Abilene, out where the West begins in earnest and nobody honks at a slow dock turn. The song got there first, but the load still needed a truck.",
        category: "radio_songs",
        inspiration: "George Hamilton IV - Abilene",
        hidden: false,
    },
    Achievement {
        id: "radio_faded_out",
        name: "Somewhere in the Static",
        description: "You rode a station all the way to the end of its reach, hiss creeping in under the music until the last of it went. Nobody hung up on you. The hill just got in the way.",
        category: "radio_songs",
        inspiration: "Harry Chapin - W.O.L.D.",
        hidden: false,
    },
    Achievement {
        id: "radio_fringe_catch",
        name: "Skip on the Far End",
        description: "You pulled in a station from far outside anything it has business reaching, flickering in and out at highway speed. Height is range, and you were up where the air is thin.",
        category: "radio_songs",
        inspiration: "Wall of Voodoo - Mexican Radio",
        hidden: false,
    },
    Achievement {
        id: "radio_three_states",
        name: "Same Song, Three State Lines",
        description: "One station carried you across three states before you finally lost it. Somewhere back there a transmitter is still trying.",
        category: "radio_songs",
        inspiration: "Golden Earring - Radar Love",
        hidden: false,
    },
    Achievement {
        id: "radio_dial_wanderer",
        name: "Worked the Whole Dial",
        description: "Twenty-five different stations found and left behind. You are not listening to the radio so much as reading the country off it.",
        category: "radio_songs",
        inspiration: "The Carpenters - Yesterday Once More",
        hidden: false,
    },
    Achievement {
        id: "jake_only_descent",
        name: "Down the Mountain on the Jake",
        description: "Two miles of real downgrade and you never once put a foot on the service brake. The engine held the whole thing, and the drums came off that hill as cool as they went on.",
        category: "road",
        inspiration: "C.W. McCall - Black Bear Road",
        hidden: false,
    },
    Achievement {
        id: "brake_smoke",
        name: "Smoke, Smoke, Smoke Those Drums",
        description: "You cooked the brakes hot enough to start losing them. They came back. Next hill, try the gear you should have been in.",
        category: "road",
        inspiration: "Tex Williams - Smoke! Smoke! Smoke! (That Cigarette)",
        hidden: false,
    },
    Achievement {
        id: "predictive_crest",
        name: "No Mountain High Enough",
        description: "You let cruise read the hill before you got to it: it banked a little speed on the flat and carried it up a grade that would have taken it off you. Nothing you had to do about it.",
        category: "road",
        inspiration: "Marvin Gaye & Tammi Terrell - Ain't No Mountain High Enough",
        hidden: false,
    },
    Achievement {
        id: "thrifty_run",
        name: "Sipping It All the Way",
        description: "A whole delivery run at better than eight miles to the gallon. Light foot, early lift, and a truck that was in the right gear for once.",
        category: "road",
        inspiration: "Eddie Rabbitt - Drivin' My Life Away",
        hidden: false,
    },
    Achievement {
        id: "five_tractors",
        name: "Whatever the Yard Has Free",
        description: "Five different tractors under you. Slip-seating means no truck is yours, and you have started noticing which of the spares pulls and which one just makes noise.",
        category: "career",
        inspiration: "Red Simpson - Roll, Truck, Roll",
        hidden: false,
    },
    Achievement {
        id: "every_fleet_tier",
        name: "Every Rung of the Yard",
        description: "From the trainer rig to first pick of the lot, you have driven something out of every band the carrier keeps. The good iron was worth waiting for.",
        category: "career",
        inspiration: "Waylon Jennings - Are You Sure Hank Done It This Way",
        hidden: false,
    },
    Achievement {
        id: "christmas_delivery",
        name: "Hard Candy Christmas Run",
        description: "You signed for a load on Christmas Day. The dock was quiet, the receiver was nice about it, and somewhere a table went ahead without you.",
        category: "weather_seasons",
        inspiration: "Dolly Parton - Hard Candy Christmas",
        hidden: false,
    },
    Achievement {
        id: "friday_thirteenth",
        name: "Superstition, Signed For",
        description: "Delivered on a Friday the thirteenth without a scratch on you. Whatever was supposed to happen took the day off.",
        category: "hidden",
        inspiration: "Stevie Wonder - Superstition",
        hidden: true,
    },
    Achievement {
        id: "new_year_run",
        name: "Working Through the Countdown",
        description: "Midnight on New Year's found you between two towns with the heater on. Somebody somewhere was counting backwards. You were counting mile markers.",
        category: "hidden",
        inspiration: "U2 - New Year's Day",
        hidden: true,
    },
    Achievement {
        id: "five_hundred_mile_run",
        name: "And Five Hundred More",
        description: "One dispatch, over a thousand miles, start to finish. Long enough that the weather changed its mind twice and you stopped noticing the radio.",
        category: "road",
        inspiration: "The Proclaimers - I'm Gonna Be (500 Miles)",
        hidden: false,
    },
    Achievement {
        id: "never_fought_the_law",
        name: "Never Fought the Law",
        description: "Fifty deliveries and not one ticket. No arguing at the window, no citation in the door pocket, no story to tell about it either.",
        category: "road",
        inspiration: "The Bobby Fuller Four - I Fought the Law",
        hidden: false,
    },
    Achievement {
        id: "night_shift_regular",
        name: "Night Moves on the Interstate",
        description: "Ten loads signed for in the small hours. You have gone properly nocturnal: empty lanes, cheap fuel, and receivers who are surprised to see anybody.",
        category: "road",
        inspiration: "Bob Seger - Night Moves",
        hidden: false,
    },
    Achievement {
        id: "coffee_regular",
        name: "One More Cup for the Road",
        description: "Twenty-five breaks taken properly, and every one of them started at a coffee pot of dubious reputation. It is not the coffee. It is the sitting down.",
        category: "working_day",
        inspiration: "Bob Dylan - One More Cup of Coffee",
        hidden: false,
    },
    Achievement {
        id: "first_drop_hook",
        name: "Drop It and Hook It",
        description: "Your first drop and hook. You backed under a trailer somebody else loaded hours ago, cranked the gear up, and were rolling before a dock would have found you a door.",
        category: "road",
        inspiration: "Red Sovine - Giddyup Go",
        hidden: false,
    },
    Achievement {
        id: "hooked_a_bad_one",
        name: "You Get What You Get",
        description: "You hooked a trailer out of a drop yard and found a write-up on the walk-around. Somebody parked it, signed for it, and went home. Now it is yours.",
        category: "road",
        inspiration: "Little Feat - Willin'",
        hidden: false,
    },
    Achievement {
        id: "refused_the_trailer",
        name: "Send It Back",
        description: "You walked a trailer, found what was wrong with it, and refused it. Thirty minutes for the swap, and the write-up stayed with the people whose problem it was.",
        category: "road",
        inspiration: "Johnny Paycheck - Take This Job and Shove It",
        hidden: false,
    },
    Achievement {
        id: "first_delivery_drop",
        name: "Leave It Where It Lies",
        description: "Your first drop at the receiving end. They keep the whole trailer, freight and all, you hook a clean empty, and you are back on the road before a dock would have called your number.",
        category: "road",
        inspiration: "The Band - The Weight",
        hidden: false,
    },
    Achievement {
        id: "dropped_the_bad_one",
        name: "Somebody Else's Turn",
        description: "You dragged a trailer with a write-up on it all the way across the country and left it in the receiver's yard. It is their problem now. You did check the lights at every stop.",
        category: "road",
        inspiration: "Hank Williams - Move It On Over",
        hidden: false,
    },
    Achievement {
        id: "detention_paid",
        name: "Paid to Sit Still",
        description: "A shipper held you past the free time and the carrier billed them for it. The clock was the only thing working, and for once it was working for you.",
        category: "road",
        inspiration: "Otis Redding - (Sittin' On) The Dock of the Bay",
        hidden: false,
    },
    Achievement {
        id: "sixty_nine_mph",
        name: "Summer of Sixty-Nine",
        description: "You held it at exactly sixty-nine miles an hour for a solid mile. The number has no significance whatsoever. You know precisely what you did.",
        category: "hidden",
        inspiration: "Bryan Adams - Summer of '69",
        hidden: true,
    },
    Achievement {
        id: "eighty_eight_mph",
        name: "Where We're Going, We Need Roads",
        description: "Eighty-eight miles an hour in a loaded truck. Nothing happened, nowhere else and no other year. Just a very fast truck and a very brief lapse of judgment.",
        category: "hidden",
        inspiration: "Huey Lewis and the News - The Power of Love",
        hidden: true,
    },
    Achievement {
        id: "sixteen_tons",
        name: "Another Day Older",
        description: "You have moved sixteen tons in a single load, and what did you get. A settlement line, a sore back, and a dispatcher already asking about the next one.",
        category: "road",
        inspiration: "Tennessee Ernie Ford - Sixteen Tons",
        hidden: false,
    },
    Achievement {
        id: "one_for_the_road",
        name: "One More for the Ditch",
        description: "A load delivered after midnight, on fumes, in the rain, still on time. Everything went wrong slowly enough that none of it managed to matter.",
        category: "road",
        inspiration: "Tom Waits - One for My Baby (and One More for the Road)",
        hidden: false,
    },
    Achievement {
        id: "fifty_five_mph",
        name: "Wrong Game, No Limit",
        description: "It isn't the mid-90s anymore like Jim Kitchen had you believe in Trucker. It's okay, floor it and hit 88.",
        category: "hidden",
        inspiration: "Sammy Hagar - I Can't Drive 55",
        hidden: true,
    },
    Achievement {
        id: "ten_four_day",
        name: "Copy That, October",
        description: "A load settled on the fourth of October, which every driver reads as ten-four. Some white knight on the channel started it, and by noon the whole band was saying the date back.",
        category: "hidden",
        inspiration: "Cledus Maggard and the Citizen's Band - The White Knight",
        hidden: true,
    },
];
