"""Frozen legacy city aliases for pre-slug saves.

Generated once by tools/migrate_city_slugs.py when the city keys moved
from bare display names to stable slugs. Old saves persist the bare
names (current city, trip city sequences, job origins) and facility IDs
derived from them; the world resolves both through this map. Do not
regenerate or extend it for new cities -- a future city reusing one of
these names must not capture saves that meant the original.
"""

from __future__ import annotations

LEGACY_CITY_SLUGS: dict[str, str] = {
    "Abilene": "abilene_tx_us",
    "Akron": "akron_oh_us",
    "Albany": "albany_ny_us",
    "Albert Lea": "albert_lea_mn_us",
    "Albuquerque": "albuquerque_nm_us",
    "Allentown": "allentown_pa_us",
    "Amarillo": "amarillo_tx_us",
    "Ann Arbor": "ann_arbor_mi_us",
    "Asheville": "asheville_nc_us",
    "Athens": "athens_ga_us",
    "Atlanta": "atlanta_ga_us",
    "Atlantic City": "atlantic_city_nj_us",
    "Augusta": "augusta_ga_us",
    "Aurora": "aurora_il_us",
    "Austin": "austin_tx_us",
    "Bakersfield": "bakersfield_ca_us",
    "Baltimore": "baltimore_md_us",
    "Bangor": "bangor_me_us",
    "Baton Rouge": "baton_rouge_la_us",
    "Beaumont": "beaumont_tx_us",
    "Beckley": "beckley_wv_us",
    "Bellingham": "bellingham_wa_us",
    "Billings": "billings_mt_us",
    "Binghamton": "binghamton_ny_us",
    "Birmingham": "birmingham_al_us",
    "Bismarck": "bismarck_nd_us",
    "Bloomington": "bloomington_il_us",
    "Boise": "boise_id_us",
    "Boston": "boston_ma_us",
    "Bridgeport": "bridgeport_ct_us",
    "Brownsville": "brownsville_tx_us",
    "Buffalo": "buffalo_ny_us",
    "Burlington": "burlington_vt_us",
    "Cape Coral": "cape_coral_fl_us",
    "Cedar Rapids": "cedar_rapids_ia_us",
    "Champaign": "champaign_il_us",
    "Charleston": "charleston_sc_us",
    "Charleston, West Virginia": "charleston_wv_us",
    "Charlotte": "charlotte_nc_us",
    "Chattanooga": "chattanooga_tn_us",
    "Cheyenne": "cheyenne_wy_us",
    "Chicago": "chicago_il_us",
    "Chico": "chico_ca_us",
    "Cincinnati": "cincinnati_oh_us",
    "Clarksville": "clarksville_tn_us",
    "Cleveland": "cleveland_oh_us",
    "College Station": "college_station_tx_us",
    "Colorado Springs": "colorado_springs_co_us",
    "Columbia": "columbia_sc_us",
    "Columbia, Missouri": "columbia_mo_us",
    "Columbus": "columbus_oh_us",
    "Coral Springs": "coral_springs_fl_us",
    "Corpus Christi": "corpus_christi_tx_us",
    "Dallas": "dallas_tx_us",
    "Davenport": "davenport_ia_us",
    "Dayton": "dayton_oh_us",
    "Decatur": "decatur_il_us",
    "Denver": "denver_co_us",
    "Des Moines": "des_moines_ia_us",
    "Detroit": "detroit_mi_us",
    "Dodge City": "dodge_city_ks_us",
    "Dover": "dover_de_us",
    "Duluth": "duluth_mn_us",
    "Eau Claire": "eau_claire_wi_us",
    "El Paso": "el_paso_tx_us",
    "Elko": "elko_nv_us",
    "Enid": "enid_ok_us",
    "Erie": "erie_pa_us",
    "Escanaba": "escanaba_mi_us",
    "Eugene": "eugene_or_us",
    "Evansville": "evansville_in_us",
    "Everett": "everett_wa_us",
    "Fairfield": "fairfield_ca_us",
    "Fargo": "fargo_nd_us",
    "Fayetteville": "fayetteville_nc_us",
    "Flint": "flint_mi_us",
    "Fort Collins": "fort_collins_co_us",
    "Fort Smith": "fort_smith_ar_us",
    "Fort Wayne": "fort_wayne_in_us",
    "Fort Worth": "fort_worth_tx_us",
    "Fresno": "fresno_ca_us",
    "Gainesville": "gainesville_fl_us",
    "Garden City": "garden_city_ks_us",
    "Gary": "gary_in_us",
    "Grand Island": "grand_island_ne_us",
    "Grand Rapids": "grand_rapids_mi_us",
    "Green Bay": "green_bay_wi_us",
    "Greensboro": "greensboro_nc_us",
    "Greenville": "greenville_sc_us",
    "Gulfport": "gulfport_ms_us",
    "Hagerstown": "hagerstown_md_us",
    "Harrisburg": "harrisburg_pa_us",
    "Harrisonburg": "harrisonburg_va_us",
    "Hartford": "hartford_ct_us",
    "Hibbing": "hibbing_mn_us",
    "Houghton": "houghton_mi_us",
    "Houston": "houston_tx_us",
    "Huntsville": "huntsville_al_us",
    "Idaho Falls": "idaho_falls_id_us",
    "Indianapolis": "indianapolis_in_us",
    "Iron Mountain": "iron_mountain_mi_us",
    "Jackson": "jackson_ms_us",
    "Jackson, Michigan": "jackson_mi_us",
    "Jacksonville": "jacksonville_fl_us",
    "Johnson City": "johnson_city_tn_us",
    "Joplin": "joplin_mo_us",
    "Kalamazoo": "kalamazoo_mi_us",
    "Kansas City": "kansas_city_mo_us",
    "Kenosha": "kenosha_wi_us",
    "Killeen": "killeen_tx_us",
    "Knoxville": "knoxville_tn_us",
    "La Crosse": "la_crosse_wi_us",
    "Lafayette": "lafayette_la_us",
    "Lafayette, Indiana": "lafayette_in_us",
    "Lakeland": "lakeland_fl_us",
    "Lancaster": "lancaster_ca_us",
    "Lansing": "lansing_mi_us",
    "Laredo": "laredo_tx_us",
    "Las Cruces": "las_cruces_nm_us",
    "Las Vegas": "las_vegas_nv_us",
    "Lawton": "lawton_ok_us",
    "Lexington": "lexington_ky_us",
    "Lincoln": "lincoln_ne_us",
    "Little Rock": "little_rock_ar_us",
    "Los Angeles": "los_angeles_ca_us",
    "Louisville": "louisville_ky_us",
    "Lubbock": "lubbock_tx_us",
    "Macon": "macon_ga_us",
    "Madison": "madison_wi_us",
    "Manchester": "manchester_nh_us",
    "Mankato": "mankato_mn_us",
    "Marquette": "marquette_mi_us",
    "McAllen": "mcallen_tx_us",
    "McKinney": "mckinney_tx_us",
    "Medford": "medford_or_us",
    "Memphis": "memphis_tn_us",
    "Miami": "miami_fl_us",
    "Midland": "midland_tx_us",
    "Milwaukee": "milwaukee_wi_us",
    "Minneapolis": "minneapolis_mn_us",
    "Missoula": "missoula_mt_us",
    "Mobile": "mobile_al_us",
    "Montgomery": "montgomery_al_us",
    "Montpelier": "montpelier_vt_us",
    "Morgantown": "morgantown_wv_us",
    "Murfreesboro": "murfreesboro_tn_us",
    "Muskegon": "muskegon_mi_us",
    "Nashville": "nashville_tn_us",
    "New Haven": "new_haven_ct_us",
    "New Orleans": "new_orleans_la_us",
    "New York": "new_york_ny_us",
    "Newark": "newark_nj_us",
    "Newport": "newport_ri_us",
    "Norfolk": "norfolk_va_us",
    "North Platte": "north_platte_ne_us",
    "Oceanside": "oceanside_ca_us",
    "Oklahoma City": "oklahoma_city_ok_us",
    "Olympia": "olympia_wa_us",
    "Omaha": "omaha_ne_us",
    "Orlando": "orlando_fl_us",
    "Oxnard": "oxnard_ca_us",
    "Palm Bay": "palm_bay_fl_us",
    "Pendleton": "pendleton_or_us",
    "Peoria": "peoria_il_us",
    "Philadelphia": "philadelphia_pa_us",
    "Phoenix": "phoenix_az_us",
    "Pittsburgh": "pittsburgh_pa_us",
    "Pocatello": "pocatello_id_us",
    "Port Huron": "port_huron_mi_us",
    "Port Saint Lucie": "port_saint_lucie_fl_us",
    "Portland": "portland_or_us",
    "Portland, Maine": "portland_me_us",
    "Portsmouth": "portsmouth_nh_us",
    "Providence": "providence_ri_us",
    "Provo": "provo_ut_us",
    "Pueblo": "pueblo_co_us",
    "Raleigh": "raleigh_nc_us",
    "Rapid City": "rapid_city_sd_us",
    "Reno": "reno_nv_us",
    "Richmond": "richmond_va_us",
    "Riverside": "riverside_ca_us",
    "Roanoke": "roanoke_va_us",
    "Rochester": "rochester_ny_us",
    "Rochester, Minnesota": "rochester_mn_us",
    "Rock Springs": "rock_springs_wy_us",
    "Rockford": "rockford_il_us",
    "Rolla": "rolla_mo_us",
    "Roseburg": "roseburg_or_us",
    "Sacramento": "sacramento_ca_us",
    "Saginaw": "saginaw_mi_us",
    "Salem": "salem_or_us",
    "Salina": "salina_ks_us",
    "Salinas": "salinas_ca_us",
    "Salisbury": "salisbury_md_us",
    "Salt Lake City": "salt_lake_city_ut_us",
    "San Angelo": "san_angelo_tx_us",
    "San Antonio": "san_antonio_tx_us",
    "San Diego": "san_diego_ca_us",
    "San Francisco": "san_francisco_ca_us",
    "San Jose": "san_jose_ca_us",
    "Santa Ana": "santa_ana_ca_us",
    "Santa Maria": "santa_maria_ca_us",
    "Santa Rosa": "santa_rosa_ca_us",
    "Sault Ste. Marie": "sault_ste_marie_mi_us",
    "Savannah": "savannah_ga_us",
    "Scranton": "scranton_pa_us",
    "Seattle": "seattle_wa_us",
    "Shreveport": "shreveport_la_us",
    "Sioux City": "sioux_city_ia_us",
    "Sioux Falls": "sioux_falls_sd_us",
    "South Bend": "south_bend_in_us",
    "Spokane": "spokane_wa_us",
    "Springfield": "springfield_mo_us",
    "Springfield, Illinois": "springfield_il_us",
    "Springfield, Massachusetts": "springfield_ma_us",
    "St. Cloud": "st_cloud_mn_us",
    "St. Louis": "st_louis_mo_us",
    "Stockton": "stockton_ca_us",
    "Syracuse": "syracuse_ny_us",
    "Tacoma": "tacoma_wa_us",
    "Tallahassee": "tallahassee_fl_us",
    "Tampa": "tampa_fl_us",
    "Toledo": "toledo_oh_us",
    "Topeka": "topeka_ks_us",
    "Traverse City": "traverse_city_mi_us",
    "Trenton": "trenton_nj_us",
    "Tri-Cities": "tri_cities_wa_us",
    "Tucson": "tucson_az_us",
    "Tulsa": "tulsa_ok_us",
    "Tuscaloosa": "tuscaloosa_al_us",
    "Twin Falls": "twin_falls_id_us",
    "Tyler": "tyler_tx_us",
    "Valencia": "valencia_ca_us",
    "Victorville": "victorville_ca_us",
    "Virginia Beach": "virginia_beach_va_us",
    "Visalia": "visalia_ca_us",
    "Waco": "waco_tx_us",
    "Washington": "washington_dc_us",
    "Wausau": "wausau_wi_us",
    "West Palm Beach": "west_palm_beach_fl_us",
    "Wichita": "wichita_ks_us",
    "Wichita Falls": "wichita_falls_tx_us",
    "Willmar": "willmar_mn_us",
    "Wilmington": "wilmington_nc_us",
    "Wilmington, Delaware": "wilmington_de_us",
    "Winchester": "winchester_va_us",
    "Winona": "winona_mn_us",
    "Worcester": "worcester_ma_us",
    "Yakima": "yakima_wa_us",
}
