"""Cities whose freight market is a stand-in (generated;
``tools/gen_stand_in_markets.py``).

Not one of these cities has a single facility whose endpoint the
freight-site screen accepts, so nothing behind any of them was surveyed.
They are stamped with ONE yard instead of the four-plus every other
market gets: a town with no mapped freight is still a place a load can
come from, and four invented warehouses there are four chances to hear a
story the map cannot back (owner ruling, 2026-09-20 -- if it is real,
bake it; if not, do not pretend).

The reference implementation's copy of the Rust
``world_constants/stand_in_markets.rs``. The build tools read the world
through this side, so the two have to agree or the data layers describe
facilities the game does not create.
"""

STAND_IN_MARKET_CITY_KEYS = frozenset(
    {
        "ada_ok_us",
        "alamo_nv_us",
        "altus_ok_us",
        "anderson_in_us",
        "atoka_ok_us",
        "austin_nv_us",
        "baker_city_or_us",
        "battle_mountain_nv_us",
        "billings_mt_us",
        "bishop_ca_us",
        "blythe_ca_us",
        "boise_city_ok_us",
        "bozeman_mt_us",
        "brownwood_tx_us",
        "buffalo_wy_us",
        "bullhead_city_az_us",
        "camp_verde_az_us",
        "cape_charles_va_us",
        "carson_city_nv_us",
        "cedar_city_ut_us",
        "chico_ca_us",
        "childress_tx_us",
        "clarendon_tx_us",
        "clarksdale_ms_us",
        "colby_ks_us",
        "columbus_ne_us",
        "cottonwood_az_us",
        "crescent_city_ca_us",
        "crestview_fl_us",
        "cumberland_md_us",
        "del_rio_tx_us",
        "delta_co_us",
        "devils_lake_nd_us",
        "douglas_az_us",
        "durango_co_us",
        "edwards_co_us",
        "ely_nv_us",
        "eureka_nv_us",
        "fallon_nv_us",
        "fernley_nv_us",
        "fort_dodge_ia_us",
        "fort_stockton_tx_us",
        "gallup_nm_us",
        "glasgow_mt_us",
        "glendive_mt_us",
        "globe_az_us",
        "grants_pass_or_us",
        "green_river_ut_us",
        "havre_mt_us",
        "hazard_ky_us",
        "hereford_tx_us",
        "hibbing_mn_us",
        "hinesville_ga_us",
        "holbrook_az_us",
        "hot_springs_sd_us",
        "indio_ca_us",
        "jacksboro_tx_us",
        "jacksonville_nc_us",
        "junction_tx_us",
        "kellogg_id_us",
        "la_grande_or_us",
        "lake_city_fl_us",
        "lake_havasu_city_az_us",
        "lawton_ok_us",
        "lexington_ne_us",
        "libby_mt_us",
        "liberal_ks_us",
        "limon_co_us",
        "lone_pine_ca_us",
        "lumberton_nc_us",
        "lusk_wy_us",
        "mammoth_lakes_ca_us",
        "marble_falls_tx_us",
        "marshalltown_ia_us",
        "mccall_id_us",
        "mcminnville_or_us",
        "minot_nd_us",
        "moab_ut_us",
        "mojave_ca_us",
        "mount_shasta_ca_us",
        "naples_fl_us",
        "natchitoches_la_us",
        "nephi_ut_us",
        "newport_ri_us",
        "north_port_fl_us",
        "oceanside_ca_us",
        "ogallala_ne_us",
        "ontario_or_us",
        "orange_tx_us",
        "ozona_tx_us",
        "page_az_us",
        "pagosa_springs_co_us",
        "paintsville_ky_us",
        "palm_coast_fl_us",
        "payson_az_us",
        "pierre_sd_us",
        "pikeville_ky_us",
        "poplar_bluff_mo_us",
        "port_huron_mi_us",
        "quincy_il_us",
        "raton_nm_us",
        "rawlins_wy_us",
        "richfield_ut_us",
        "ridgecrest_ca_us",
        "rocky_mount_nc_us",
        "rolla_mo_us",
        "rutland_vt_us",
        "santa_barbara_ca_us",
        "sault_ste_marie_mi_us",
        "shelby_mt_us",
        "sheridan_wy_us",
        "sierra_vista_az_us",
        "silverthorne_co_us",
        "socorro_nm_us",
        "spearfish_sd_us",
        "spring_hill_fl_us",
        "stephenville_tx_us",
        "stratford_tx_us",
        "superior_mt_us",
        "susanville_ca_us",
        "the_dalles_or_us",
        "tonopah_nv_us",
        "trinidad_co_us",
        "tucumcari_nm_us",
        "uvalde_tx_us",
        "van_horn_tx_us",
        "vineland_nj_us",
        "walsenburg_co_us",
        "watertown_ny_us",
        "wells_nv_us",
        "west_wendover_nv_us",
        "wheatland_wy_us",
        "winona_mn_us",
        "winslow_az_us",
        "wolf_point_mt_us",
        "yreka_ca_us",
        "yuma_az_us",
    }
)
